#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="${ROOT}/src"
OUT="${ROOT}/dist/pg-diagnose.sh"
TMP="${OUT}.tmp"

mkdir -p "${ROOT}/dist"
trap 'rm -f "$TMP"' EXIT

{
  echo "#!/usr/bin/env bash"
  echo "set -euo pipefail"
  echo "# generated by build.sh from src/ — edit modules in src/, not this file"
  while IFS= read -r m || [[ -n "$m" ]]; do
    [[ -z "$m" || "$m" == \#* ]] && continue
    f="${SRC}/${m}"
    if [[ ! -f "$f" ]]; then
      echo "missing module listed in src/MODULES: ${m}" >&2
      exit 1
    fi
    sed -e '/^#!/d' -e '/^set -euo pipefail$/d' "$f"
    printf '\n'
  done < "${SRC}/MODULES"
  echo 'run_cli "$@"'
} > "$TMP"

chmod +x "$TMP"
bash "$TMP" --help >/dev/null
bash "$TMP" --legend >/dev/null
mv "$TMP" "$OUT"
echo "wrote ${OUT}"