#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="${ROOT}/src"
OUT="${ROOT}/dist/pg-diagnose.sh"
TMP="${OUT}.tmp"

mkdir -p "${ROOT}/dist"
trap 'rm -f "$TMP"' EXIT

{
  echo "#!/usr/bin/env bash"
  echo "set -euo pipefail"
  echo "# generated by build.sh from src/ — edit modules in src/, not this file"
  for m in "${SRC}"/lib/*.sh "${SRC}"/helpers/*.sh "${SRC}"/phases/*.sh "${SRC}"/main.sh; do
    if [[ ! -f "$m" ]]; then
      echo "missing module: $m" >&2
      exit 1
    fi
    sed -e '/^#!/d' -e '/^set -euo pipefail$/d' "$m"
    printf '\n'
  done
  echo 'run_cli "$@"'
} > "$TMP"

chmod +x "$TMP"
bash "$TMP" --help >/dev/null
mv "$TMP" "$OUT"
echo "wrote ${OUT}"