#!/usr/bin/env bash

emit_sugg_catalog() {
  cat <<'CATALOG_SQL'
CREATE TEMP TABLE sugg_cat (category text PRIMARY KEY, why text, risk text, skip_if text);

INSERT INTO sugg_cat VALUES
('Missing ANN index (vector distance sort)',
 'ORDER BY a vector distance computes the distance for every candidate row and sorts the full set on every call. An HNSW index serves ORDER BY <col> <op> <param> LIMIT n directly, with APPROXIMATE results (recall vs speed: hnsw.ef_search). The index is used only when the ORDER BY expression is the bare ascending distance — rewrite forms like (constant - (col <op> v)) DESC to the bare distance and derive similarity in the select list. A partial index is smaller, but every query must repeat the predicate verbatim.',
 'Approximate results; combined with selective filters it can return fewer than LIMIT rows (pgvector >= 0.8: hnsw.iterative_scan). The build is memory/time heavy (maintenance_work_mem) and every write to the column updates the graph.',
 'The workload aggregates over all matching rows, exact ordering is required, or the ORDER BY cannot be rewritten to the bare distance expression.'),
('Missing GIN index (JSONB/array filter)',
 'A JSONB/array operator (@>, && or <@) is tested row-by-row in a plan Filter: every candidate row is fetched and checked. A GIN index serves these operators directly.',
 'GIN indexes are larger and slower to update than btree: every write to the table also updates the index.',
 'Queries always pair the column with a selective btree condition that already narrows to few rows. A partial GIN can shrink it.'),
('Existing GIN index not chosen by the planner',
 'Statements filter with @>/&&/<@ at high mean time and a matching GIN index exists, but its lifetime scan count is far below the statements'' combined calls — most executions take another path. Common causes: stale or insufficient column statistics (ANALYZE; consider SET STATISTICS 1000 on the column), a competing ORDER BY + LIMIT btree path, or cost settings. Capture the real plan with a representative value before changing anything.',
 'No DDL — investigation finding.',
 'The index was created recently (its scan counter covers less time than the call counters), or the heavy calls predate the index.'),
('Missing trigram index (pattern-match filter)',
 'A LIKE/ILIKE/regex filter is tested row-by-row: every candidate row is fetched and pattern-matched. A pg_trgm GIN index serves these operators directly, including leading-wildcard patterns. Patterns shorter than 3 characters cannot use it.',
 'Trigram GIN indexes are large and slow down every write to the table.',
 'The pattern column is always paired with a selective equality that already narrows to few rows, or the predicate sits inside an OR spanning other columns or subqueries (one index alone cannot serve it).'),
('Missing index for sorted pagination',
 'Limit above Sort above a scan: every call scans and sorts the full matching set before pagination. An ordered index (equality/IS NULL prefix columns first, then the sort column) lets Limit stop early.',
 'Every write to the table must also update the new index. Deep OFFSET stays O(offset) even with the index — keyset pagination is the durable fix.',
 'The ORDER BY column is about to change, the predicate is not stable across callers, or the suggested shape does not match all callers.'),
('Ordered index exists but planner not choosing it (sorted pagination)',
 'The query is Limit-over-Sort, and an existing index already provides the requested order for this predicate, but the recorded plan sorts anyway. Common causes: stale statistics on the filter columns, a more selective competing path, or cost settings. Investigate the real plan before adding anything.',
 'No DDL — investigation finding.',
 'The index was created after the bulk of the recorded calls.'),
('Cheap plan but high observed runtime',
 'The generic plan cost is tiny relative to the observed mean time: time is going somewhere the planner does not model — detoasting wide columns (check toast reads in evidence), lock waits, network/result transfer of wide rows, or runtime plan flips with real parameters. Narrow the SELECT list (avoid wide text/jsonb columns when unused), check pg_stat_io timings (requires track_io_timing=on), and capture a real plan with real parameters.',
 'No DDL — investigation finding.',
 'The statement intentionally streams wide rows and the latency is accepted.'),
('Query spills to disk during sort/hash',
 'The sort/hash step does not fit in memory and spills to disk. The default fix is restructuring (pre-aggregate, paginate before aggregation, narrower sort keys) — raising work_mem only relocates the cost into RAM.',
 'No DDL.',
 'Spill volume is small relative to call frequency and latency is acceptable.'),
('Repeated expensive aggregate — cache or materialize',
 'A statement whose plan aggregates (GROUP BY / COUNT) runs repeatedly at high mean time and returns few rows: each call recomputes over the same large data set. Cache the result in the application, maintain a summary table, or compute it periodically.',
 'No DDL.',
 'Each call genuinely needs exact, fresh results and the data changes faster than any acceptable cache TTL.'),
('Stale or missing planner statistics',
 'Row estimates are stale or absent: the planner makes wrong scan and join choices that burn CPU. Plan-based suggestions in this report are unreliable for queries touching this table until ANALYZE runs.',
 'ANALYZE reads a row sample under a brief ShareUpdateExclusiveLock — safe, no data changes. If a dead-tuple suggestion targets the same table, run VACUUM (ANALYZE) once instead of both.',
 'A bulk load or migration is still writing to this table — analyze after it finishes.'),
('Expensive ANALYZE from statistics on vector columns',
 'The planner gains nothing from per-column statistics on vector types (ANN indexes do not use them), but ANALYZE detoasts and samples every value, making stats refreshes slow for the whole table. Disabling statistics for the column removes that cost.',
 'None for planning. Reversible with SET STATISTICS -1.',
 'Some external tooling reads pg_stats for this column (rare).'),
('Autoanalyze has never run on a write-heavy table',
 'The table accumulates writes but autoanalyze has never fired: with the default scale factor the churn stays below the trigger threshold, so statistics refresh only when run manually and plans drift between refreshes (visible as high run-to-run variance). Per-table thresholds make refreshes proportional to actual churn.',
 'ANALYZE runs become more frequent (brief ShareUpdateExclusiveLock and sampling I/O). If an expensive-ANALYZE suggestion targets the same table, apply it first or every run stays slow.',
 'The table was bulk-loaded recently, statistics were reset recently, or an external maintenance job already owns ANALYZE scheduling.'),
('Dead tuple bloat slowing scans',
 'Every scan steps over dead row versions before finding live rows. With default settings autovacuum should have fired near 17% dead, so it is not keeping up: a one-off VACUUM clears the backlog; the durable fix is per-table autovacuum tuning (see note).',
 'VACUUM generates I/O under ShareUpdateExclusiveLock. It does not shrink the file (apart from trailing empty pages) — it makes the space reusable.',
 'A long-running or idle-in-transaction session holds back cleanup (old backend_xmin) — check the idle transactions section of a full run first.'),
('WAL buffers saturating on insert',
 'wal_buffers_full is high relative to WAL records: backends frequently find the WAL buffers full and flush synchronously, adding latency and write amplification. Compare with per-backend WAL counts in pg_stat_io. wal_buffers follows shared memory sizing on managed clusters, so the durable fix may be a larger instance.',
 'No DDL — investigation finding.',
 'The counters span a stats reset or an atypical bulk-load period.'),
('Missing index on foreign key',
 'These foreign-key columns have no covering btree index: joins on them scan the whole table, and DELETE (or key-changing UPDATE) of referenced parent rows must scan the child to check the constraint. Non-key parent updates, including HOT updates, never fire RI checks. Confidence comes from plan_refs — the column appearing in predicates or join conditions of collected top-statement plans for this table; text_refs is context only, since ORMs project every column into every statement.',
 'Every write to the table must also update each new index.',
 'Parent rows are never hard-deleted AND the join path is cold. plan_refs covers only the collected top statements, so 0 does not prove the column is never joined on.'),
('Redundant index (covered by another)',
 'Key columns are a leading prefix of the covering index with matching opclass, collation, and sort options: the covering index can serve the same queries.',
 'After DROP, lookups shift to the covering index; expect a mild per-lookup cost increase when it is much larger. Recreate from the definition preserved in the evidence if the covering index is later dropped or made partial.',
 'The index is referenced by name in code, or the covering index is itself a cleanup candidate.'),
('Index extends a unique key (trailing columns cannot narrow further)',
 'The leading columns are exactly the key set of a unique index: at most one row matches any leading-key value, so the trailing columns never reduce the result further. The only remaining value is as a covering index for index-only scans returning the trailing columns.',
 'Lookups shift to the unique index; index-only scans that returned trailing columns become heap fetches.',
 'Queries do index-only scans selecting the trailing columns, or the unique index may be dropped or relaxed.'),
('Disabled trigger still in schema',
 'The trigger is disabled (tgenabled=D): it never fires but remains in the schema.',
 'Irreversible without the definition — it is preserved in the evidence.',
 'It was disabled intentionally (migration, bulk load) and will be re-enabled.'),
('Duplicate triggers',
 'Multiple user triggers with identical timing, events, column list, WHEN clause, and arguments fire the same function. One is sufficient.',
 'Irreversible without the definition — inspect pg_get_triggerdef and save it before dropping.',
 'The redundancy is intentional (e.g. separate migrations pending consolidation).'),
('Trigger on table with no writes',
 'The trigger never fires: the table has zero writes since stats reset. No runtime cost — schema noise only.',
 'Informational.',
 'Writes are periodic (jobs, imports) outside the stats window.');
CATALOG_SQL
}